import test from 'node:test';
import assert from 'node:assert/strict';
import { projectWorldSimGround, readGroundFrame, MATERIALS } from '../ground/worldsim-ground-adapter.mjs';
import { buildGroundGeometry } from '../ground/ground-geometry.mjs';
import { createWorldGroundRenderer, installSurfaceShader } from '../ground/three-ground-renderer.mjs';
// Synthetic boundary fixture, distinct from the genuine simulator demo export.
function source() {
  const cells=Array.from({length:4},(_,index)=>({index,column:index%2,row:Math.floor(index/2),elevation:.4,terrainType:'grass',surfaceWater:0,totalWaterHeight:.4,isOceanCell:false,isFlooded:false}));
  const section=fn=>({version:0,cells:cells.map((c,i)=>({index:i,...fn(i)}))});
  return {tick:7,world:{seed:29051,gridWidth:2,gridHeight:2,worldWidth:20,worldHeight:30,cellWidth:10,cellHeight:15,cells,hydrology:{version:0},soil:section(()=>({soilType:'loam',active:true,waterContent:2,saturationCapacity:4})),vegetation:section(()=>({active:true,coverage:.2})),fire:section(()=>({burnSeverity:0})),biomes:section(()=>({primaryBiome:'grassland'}))}};
}
function deepFreeze(o){if(o&&typeof o==='object'){Object.values(o).forEach(deepFreeze);Object.freeze(o);}return o;}
const frame=()=>projectWorldSimGround(source());
const transform={horizontalScale:.1,elevationScale:10,textureWorldSize:2};
test('uses frozen producer snapshot without writes; exact deterministic output',()=>{const s=deepFreeze(source());const before=JSON.stringify(s);const a=projectWorldSimGround(s);assert.deepEqual(a,projectWorldSimGround(s));assert.equal(JSON.stringify(s),before);assert.equal(a.source.tick,7);assert.throws(()=>a.channels.elevation[0]=3,TypeError);});
test('soil owner reservoir, not humidity or compatibility alias, controls wetness',()=>{const s=source();s.world.cells[0].soilMoisture=99;s.world.cells[0].humidity=1;assert.equal(projectWorldSimGround(s).channels.wetness[0],.5);});
test('vegetation uses actual coverage, not fertility or biome potential',()=>{const s=source();s.world.cells[0].fertility=1;s.world.vegetation.cells[0].coverage=0;assert.equal(projectWorldSimGround(s).channels.vegetation[0],0);});
test('zero-capacity/inactive soil and inactive vegetation remain finite',()=>{const s=source();s.world.soil.cells[0].saturationCapacity=0;s.world.soil.cells[1].active=false;s.world.vegetation.cells[0].active=false;const f=projectWorldSimGround(s);assert.equal(f.channels.wetness[0],0);assert.equal(f.channels.wetness[1],0);assert.equal(f.channels.vegetation[0],0);});
test('total water datum is read exactly once',()=>{const s=source();Object.assign(s.world.cells[0],{surfaceWater:.2,totalWaterHeight:.6});const f=projectWorldSimGround(s);assert.equal(f.channels.waterHeight[0],.6);assert.equal(f.channels.waterDepth[0],.2);});
test('producer selector changes material only, not primary biome truth',()=>{const s=source();const f=projectWorldSimGround(s,{surfaceBiome:()=> 'burned'});assert.equal(MATERIALS[f.channels.material[0]],'burned');assert.equal(f.channels.biome[0],frame().channels.biome[0]);assert.equal(f.source.surfacePolicy,'producer-worldSurfaceBiome');});
test('does not infer flood from water depth',()=>{const s=source();s.world.cells[0].surfaceWater=99;assert.equal(projectWorldSimGround(s).channels.flooded[0],0);});
test('rejects partial snapshots and wrong producer versions',()=>{const s=source();s.world.soil.cells.pop();assert.throws(()=>projectWorldSimGround(s),/full snapshot/);assert.throws(()=>projectWorldSimGround(source(),{sourceVersion:'next'}),/Unverified/);});
test('rejects index errors and inconsistent dimensions',()=>{const s=source();s.world.cells[1].column=9;assert.throws(()=>projectWorldSimGround(s),/mismatch/);s.world.cellWidth=11;assert.throws(()=>projectWorldSimGround(s),/dimensions/);});
test('rejects NaN, Infinity, unexpected enums and nonboolean flags',()=>{for(const [key,value]of [['elevation',NaN],['totalWaterHeight',Infinity],['terrainType','alien'],['isFlooded',1]]){const s=source();s.world.cells[0][key]=value;assert.throws(()=>projectWorldSimGround(s));}});
test('JSON packet roundtrip is detached and deeply frozen',()=>{const a=frame(),raw=JSON.parse(JSON.stringify(a)),b=readGroundFrame(raw);raw.channels.elevation[0]=6;assert.equal(b.channels.elevation[0],.4);assert.deepEqual(b,a);assert.ok(Object.isFrozen(b.source.versions));});
test('rejects malformed channel ranges/enums and oversized grids',()=>{for(const [key,value]of [['wetness',2],['material',99],['biome',-1],['flooded',.2],['waterDepth',-1]]){const a=JSON.parse(JSON.stringify(frame()));a.channels[key][0]=value;assert.throws(()=>readGroundFrame(a));}const s=source();s.world.gridWidth=99999;assert.throws(()=>projectWorldSimGround(s),/65536/);});
test('requires explicit visual coordinate transform',()=>{assert.throws(()=>buildGroundGeometry(frame()),/horizontalScale/);assert.throws(()=>buildGroundGeometry(frame(),{...transform,elevationScale:0}));});
test('geometry has six vertices/cell, global UVs and normalized upward normals',()=>{const b=buildGroundGeometry(frame(),transform);assert.equal(b.terrain[0].position.length,4*6*3);assert.deepEqual(b.bounds,{width:2,depth:3});assert.ok(b.terrain[0].normal.every((n,i)=>n===(i%3===1?1:0)));assert.deepEqual(Array.from(b.terrain[0].uv.slice(0,2)),[-.5,-.75]);assert.equal(b.water.position.length,0);});
test('shared boundary heights/normals agree across material batches',()=>{const s=source();s.world.cells[1].elevation=.8;s.world.biomes.cells[1].primaryBiome='rock';const b=buildGroundGeometry(projectWorldSimGround(s),transform);const seen=new Map();for(const batch of b.terrain)for(let i=0;i<batch.position.length;i+=3){const p=Array.from(batch.position.slice(i,i+3)),n=Array.from(batch.normal.slice(i,i+3)),key=`${p[0]},${p[2]}`;if(seen.has(key))assert.deepEqual({p,n},seen.get(key));else seen.set(key,{p,n});}});
test('only wet cells create water using source datum',()=>{const s=source();Object.assign(s.world.cells[0],{surfaceWater:.2,totalWaterHeight:.6});const b=buildGroundGeometry(projectWorldSimGround(s),transform);assert.equal(b.water.position.length,18);for(let i=1;i<18;i+=3)assert.equal(b.water.position[i],6);});
// Contract doubles below exercise resource ownership, not WebGL compilation.
class Group {children=[];add(x){this.children.push(x);}remove(x){this.children=this.children.filter(y=>y!==x);}}
class Geometry {attributes={};disposed=0;setAttribute(k,v){this.attributes[k]=v;}computeBoundingSphere(){}dispose(){this.disposed++;}}
class Material {disposed=0;constructor(o){Object.assign(this,o);this.color={set:v=>this.colorValue=v};this.normalScale={set:(x,y)=>this.normalXY=[x,y]};}dispose(){this.disposed++;}}
class Texture {isTexture=true;disposed=0;clone(){return new Texture();}dispose(){this.disposed++;}}
const THREE={Group,BufferGeometry:Geometry,MeshStandardMaterial:Material,BufferAttribute:class{constructor(array,itemSize){Object.assign(this,{array,itemSize});}},Mesh:class{constructor(geometry,material){Object.assign(this,{geometry,material});}},SRGBColorSpace:'srgb',NoColorSpace:'',RepeatWrapping:1000,LinearMipmapLinearFilter:1008,LinearFilter:1006};
function renderer(){return createWorldGroundRenderer({THREE,scene:new Group(),transform,maxAnisotropy:16});}
test('renderer batches materials, no-op for frozen frame, and frees old geometry',()=>{const r=renderer(),f=frame();assert.equal(r.setFrame(f),true);assert.equal(r.setFrame(f),false);assert.ok(r.root.children.length<=8);const old=r.root.children[0].geometry;r.setFrame(frame());assert.equal(old.disposed,1);r.dispose();assert.equal(r.root.children.length,0);assert.throws(()=>r.setFrame(f),/disposed/);r.dispose();});
test('invalid replacement preserves currently visible frame',()=>{const r=renderer();r.setFrame(frame());const old=r.root.children[0];assert.throws(()=>r.setFrame({}));assert.equal(r.root.children[0],old);r.dispose();});
test('texture clones own GPU resources, color space and AO UV channel',()=>{const r=renderer();r.setFrame(frame());const original=new Texture(),m=r.root.children[0].material;r.setTexture('grass','albedo',original);const owned=m.map;assert.notEqual(owned,original);assert.equal(owned.colorSpace,'srgb');assert.equal(owned.anisotropy,4);r.setTexture('grass','normal',original,{normalConvention:'directx'});assert.equal(m.normalMap.colorSpace,'');assert.deepEqual(m.normalXY,[1,-1]);r.setTexture('grass','ao',original);assert.equal(m.aoMap.channel,1);r.setTexture('grass','albedo',null);assert.equal(owned.disposed,1);r.dispose();assert.equal(original.disposed,0);});
test('shader hook guards compatibility and installs no new simulator loop',()=>{const m={};installSurfaceShader(m);assert.throws(()=>m.onBeforeCompile({vertexShader:'',fragmentShader:''}),/Unsupported/);const s={vertexShader:'#include <common>\n#include <begin_vertex>',fragmentShader:'#include <common>\n#include <color_fragment>\n#include <roughnessmap_fragment>'};m.onBeforeCompile(s);assert.match(s.vertexShader,/groundSurface/);assert.match(s.fragmentShader,/roughnessFactor = clamp/);assert.equal(m.customProgramCacheKey(),'worldsim-ground-surface-v1');});
test('mutable import object does not defeat replacement via identity cache',()=>{const r=renderer(),raw=JSON.parse(JSON.stringify(frame()));r.setFrame(raw);raw.channels.elevation[0]=.9;assert.equal(r.setFrame(raw),true);assert.equal(r.getFrame().channels.elevation[0],.9);r.dispose();});
