def patch(html):
    def rep(text, old, new, label, count=1):
        if old not in text:
            raise RuntimeError(f"missing anchor: {label}")
        return text.replace(old,new,count)
    html=html.replace("Character Prototype Studio V1.8.4","Character Prototype Studio V1.8.4.1")
    html=html.replace("V1.8.4 · Action Dynamics Inspector / Kinetic Chain QA",
                      "V1.8.4.1 · Twist Activation Hotfix / Action Template Runtime Fix")
    html=html.replace('generatorVersion:"1.8.4"','generatorVersion:"1.8.4.1"')
    html=html.replace("// Generated by Character Prototype Studio V1.8.4.1.1",
                      "// Generated by Character Prototype Studio V1.8.4.1")
    old='''function createTemplateClip(name,duration,fps,keys,loop=true,interpolation="smooth"){
  const clip=makeAnimationClip(name,duration,fps);
  clip.loop=loop;clip.interpolation=interpolation;'''
    new='''function createTemplateClip(name,duration,fps,keys,loop=true,interpolation="smooth"){
  const clip=makeAnimationClip(name,duration,fps);
  const n=String(name||"").toLowerCase();
  const motionClass=/^attack_|attack|slash|punch|kick|thrust|dodge/.test(n)?"action":
    /^run_|run|sprint/.test(n)?"run":
    /^walk_|walk|move/.test(n)?"walk":
    /^idle_|idle|stand/.test(n)?"idle":"custom";
  clip.runtime.motionClass=motionClass;
  clip.runtime.motionSpeed=motionClass==="run"?4.5:motionClass==="walk"?1.8:0;
  clip.runtime.state=n.replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")||motionClass;
  clip.loop=loop;clip.interpolation=interpolation;'''
    html=rep(html,old,new,"template motion class fix")
    anchor='''function createTemplateClip(name,duration,fps,keys,loop=true,interpolation="smooth"){'''
    migration=r'''function migrateTemplateMotionClasses(){
  let changed=0;
  for(const clip of spec.animations||[]){
    const isTemplate=clip.source?.kind==="pose-library-template";
    if(!isTemplate)continue;
    const n=String(clip.name||"").toLowerCase();
    let cls=null,speed=0;
    if(/^attack_|attack|slash|punch|kick|thrust|dodge/.test(n)){cls="action";speed=0}
    else if(/^run_|run|sprint/.test(n)){cls="run";speed=4.5}
    else if(/^walk_|walk|move/.test(n)){cls="walk";speed=1.8}
    else if(/^idle_|idle|stand/.test(n)){cls="idle";speed=0}
    if(!cls)continue;
    clip.runtime=clip.runtime||{};
    if(clip.runtime.motionClass==="custom"||!clip.runtime.motionClass){
      clip.runtime.motionClass=cls;clip.runtime.motionSpeed=speed;changed++;
    }
    if(!clip.runtime.state||clip.runtime.state==="animation"){
      clip.runtime.state=n.replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"")||cls;
    }
  }
  return changed;
}
'''
    html=rep(html,anchor,migration+anchor,"template migration helper")
    old='''function initUI(){
  ensureRuntimeSettings();ensureWeightSpec();ensureSkinSystem();migrateNaturalWalkTuning();'''
    new='''function initUI(){
  ensureRuntimeSettings();ensureWeightSpec();ensureSkinSystem();migrateNaturalWalkTuning();
  const migratedTemplateClasses=migrateTemplateMotionClasses();
  if(migratedTemplateClasses)console.info(`V1.8.4.1 migrated ${migratedTemplateClasses} template motion class(es)`);'''
    html=rep(html,old,new,"init template migration")
    old='''  const inferClass=/idle|stand/.test(inferredState)?"idle":/run|sprint/.test(inferredState)?"run":/walk|move/.test(inferredState)?"walk":/attack|hit|skill|cast/.test(inferredState)?"action":"custom";
  const inferSpeed=inferClass==="run"?4.5:inferClass==="walk"?1.8:0;
  clip.runtime={'''
    new='''  const inferClass=/idle|stand/.test(inferredState)?"idle":/run|sprint/.test(inferredState)?"run":/walk|move/.test(inferredState)?"walk":/attack|hit|skill|cast|slash|punch|kick|thrust|dodge/.test(inferredState)?"action":"custom";
  const inferSpeed=inferClass==="run"?4.5:inferClass==="walk"?1.8:0;
  const templateNeedsClass=clip.source?.kind==="pose-library-template"&&(!clip.runtime?.motionClass||clip.runtime.motionClass==="custom");
  clip.runtime={'''
    html=rep(html,old,new,"normalize template infer")
    old='''    motionClass:["idle","walk","run","action","custom"].includes(clip.runtime?.motionClass)?clip.runtime.motionClass:inferClass,
    motionSpeed:clamp(Number.isFinite(Number(clip.runtime?.motionSpeed))?Number(clip.runtime.motionSpeed):inferSpeed,0,12)'''
    new='''    motionClass:templateNeedsClass?inferClass:(["idle","walk","run","action","custom"].includes(clip.runtime?.motionClass)?clip.runtime.motionClass:inferClass),
    motionSpeed:clamp(templateNeedsClass?inferSpeed:(Number.isFinite(Number(clip.runtime?.motionSpeed))?Number(clip.runtime.motionSpeed):inferSpeed),0,12)'''
    html=rep(html,old,new,"normalize template motion class")
    old='''function renderBodyDynamicsStatus(r=bodyDynamicsState.last){
  if(!$("#bodyPhaseValue"))return;
  $("#bodyPhaseValue").textContent=(r?.phase||"idle").toUpperCase();'''
    new='''function renderBodyDynamicsStatus(r=bodyDynamicsState.last){
  if(!$("#bodyPhaseValue"))return;
  const clip=selectedAnimationClip();
  const active=!!clip?.bodyDynamics?.enabled&&clip?.runtime?.motionClass==="action";
  $("#bodyPhaseValue").textContent=active?(r?.phase||"idle").toUpperCase():"BYPASS";'''
    html=rep(html,old,new,"body active status")
    old='''  if(pill){pill.textContent=(r?.phase||"idle").toUpperCase();pill.className="pill "+(r?.phase&&r.phase!=="idle"?"good":"")}
  if(d&&r)d.textContent=`${r.actionLabel||"Action"} · Pelvis ${deg(r.pelvisY).toFixed(1)}° → Chest ${deg(r.chestY).toFixed(1)}° → Shoulder ${deg(r.shoulderY).toFixed(1)}° · move X ${(r.pelvisXMove||0).toFixed(3)}m Z ${(r.pelvisZMove||0).toFixed(3)}m`;'''
    new='''  if(pill){
    pill.textContent=active?(r?.phase||"idle").toUpperCase():"BYPASS";
    pill.className="pill "+(active&&r?.phase&&r.phase!=="idle"?"good":active?"":"warn");
  }
  if(d){
    if(!active)d.textContent=`Body Dynamics BYPASSED · motionClass=${clip?.runtime?.motionClass||"none"} · ต้องเป็น action`;
    else if(r)d.textContent=`${r.actionLabel||"Action"} · Pelvis ${deg(r.pelvisY).toFixed(1)}° → Chest ${deg(r.chestY).toFixed(1)}° → Shoulder ${deg(r.shoulderY).toFixed(1)}° · move X ${(r.pelvisXMove||0).toFixed(3)}m Z ${(r.pelvisZMove||0).toFixed(3)}m`;
  }'''
    html=rep(html,old,new,"body bypass indicator")
    old='''function createAttackTemplate(){
  addTemplateClip(createTemplateClip("Attack_PoseLibrary",0.9,30,[
    {time:0.00,pose:"idle"},
    {time:0.28,pose:"attackWindup",side:"R"},
    {time:0.48,pose:"attackImpact",side:"R"},
    {time:0.90,pose:"idle"}
  ],false,"smooth"));
}'''
    new='''function createAttackTemplate(){
  const clip=createTemplateClip("Attack_PoseLibrary",0.9,30,[
    {time:0.00,pose:"idle"},
    {time:0.28,pose:"attackWindup",side:"R"},
    {time:0.48,pose:"attackImpact",side:"R"},
    {time:0.90,pose:"idle"}
  ],false,"smooth");
  clip.runtime.motionClass="action";
  clip.runtime.state="attack_pose_library";
  clip.attackProfile.side="R";
  clip.attackProfile.style="horizontal";
  clip.attackProfile.anticipationEnd=.12;
  clip.attackProfile.windupEnd=.30;
  clip.attackProfile.impactTime=.48;
  clip.attackProfile.followThroughEnd=.70;
  clip.attackProfile.recoveryEnd=.90;
  clip.bodyDynamics.enabled=true;
  clip.bodyDynamics.actionType="slash";
  clip.bodyDynamics.preset="natural";
  clip.bodyDynamics.intensity=.92;
  addTemplateClip(clip);
}'''
    html=rep(html,old,new,"visible attack template")
    old='''            <button class="btn good grow" id="btnPreviewBodyDynamics">Preview Dynamics</button>
            <button class="btn grow" id="btnApplyBodyDynamics">Apply Settings</button>'''
    new='''            <button class="btn good grow" id="btnPreviewBodyDynamics">Preview Dynamics</button>
            <button class="btn good grow" id="btnTwistDemo">Twist Demo</button>
            <button class="btn grow" id="btnApplyBodyDynamics">Apply Settings</button>'''
    html=rep(html,old,new,"twist demo UI")
    anchor='''function previewBodyDynamicsCurrent(){'''
    demo_fn=r'''function twistDemo(){
  let clip=selectedAnimationClip();
  if(!clip||clip.runtime?.motionClass!=="action"){
    createAttackTemplate();
    clip=selectedAnimationClip();
  }
  normalizeClip(clip);
  clip.bodyDynamics.enabled=true;
  if(clip.bodyDynamics.actionType==="auto")clip.bodyDynamics.actionType="slash";
  if(clip.bodyDynamics.intensity<.85)clip.bodyDynamics.intensity=.92;
  animationState.time=0;
  if(animationState.playing||animationState.basePose)stopAnimationPlayback(true);
  startAnimationPlayback();
  toast("Twist Demo: ดู Pelvis → Chest → Shoulder ช่วง Wind-up → Impact");
}
'''
    html=rep(html,anchor,demo_fn+anchor,"twist demo function")
    anchor='''$("#btnPreviewBodyDynamics").onclick=previewBodyDynamicsCurrent;'''
    html=rep(html,anchor,anchor+'''
$("#btnTwistDemo").onclick=twistDemo;''',"twist demo binding")
    html=html.replace('localStorage.setItem("characterPrototypeStudio.v1.8.4"','localStorage.setItem("characterPrototypeStudio.v1.8.4.1"',1)
    html=html.replace(
        'const raw=localStorage.getItem("characterPrototypeStudio.v1.8.4")||localStorage.getItem("characterPrototypeStudio.v1.8.3")||',
        'const raw=localStorage.getItem("characterPrototypeStudio.v1.8.4.1")||localStorage.getItem("characterPrototypeStudio.v1.8.4")||localStorage.getItem("characterPrototypeStudio.v1.8.3")||',
        1
    )
    return html
